<?php

namespace AppBundle\Repository;

/**
 * FlatNodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlatNodeRepository extends \Doctrine\ORM\EntityRepository
{
}
