<?php

namespace AppBundle\Repository;

/**
 * NodeMetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodeMetaRepository extends \Doctrine\ORM\EntityRepository
{
}
