<?php

namespace AppBundle\Repository;

/**
 * Table_Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Table_Repository extends \Doctrine\ORM\EntityRepository
{
}
