<?php

namespace AppBundle\Repository;

/**
 * TableNodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableNodeRepository extends \Doctrine\ORM\EntityRepository
{
}
