<?php

namespace AppBundle\Repository;

/**
 * ValidationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValidationRepository extends \Doctrine\ORM\EntityRepository
{
}
